package net.pottercraft.ollivanders2.spell;

import net.pottercraft.ollivanders2.common.MagicLevel;
import net.pottercraft.ollivanders2.common.Ollivanders2Common;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Registry of every supported spell, mapping each to its implementing {@link O2Spell} subclass and {@link MagicLevel}.
 *
 * @author Azami7
 */
public enum O2SpellType {
    ABERTO(ABERTO.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    ACCIO(ACCIO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    AGNIFORS(AGNIFORS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    AGNIFORS_MAXIMA(AGNIFORS_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    AGUAMENTI(AGUAMENTI.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    ALARTE_ASCENDARE(ALARTE_ASCENDARE.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    ALIQUAM_FLOO(ALIQUAM_FLOO.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    ALOHOMORA(ALOHOMORA.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    AMATO_ANIMO_ANIMATO_ANIMAGUS(AMATO_ANIMO_ANIMATO_ANIMAGUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    ANAPNEO(ANAPNEO.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    APARECIUM(APARECIUM.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    APPARATE(APPARATE.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    AQUA_ERUCTO(AQUA_ERUCTO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    AQUA_ERUCTO_DUO(AQUA_ERUCTO_DUO.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    ARANIA_EXUMAI(ARANIA_EXUMAI.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    ARRESTO_MOMENTUM(ARRESTO_MOMENTUM.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    ASCENDIO(ASCENDIO.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    ASTROLOGIA(ASTROLOGIA.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    AVADA_KEDAVRA(AVADA_KEDAVRA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    AVIFORS(AVIFORS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    AVIS(AVIS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    AZURILLIOUS(AZURILLIOUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    BAO_ZHONG_CHA(BAO_ZHONG_CHA.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    BOMBARDA(BOMBARDA.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    BOMBARDA_MAXIMA(BOMBARDA_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    BOS(BOS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    BOTHYNUS(BOTHYNUS.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    BOTHYNUS_DUO(BOTHYNUS_DUO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    BOTHYNUS_TRIA(BOTHYNUS_TRIA.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    BOVIFORS(BOVIFORS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    BOVIFORS_MAXIMA(BOVIFORS_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    BRACKIUM_EMENDO(BRACKIUM_EMENDO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    CALAMUS(CALAMUS.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    CANIFORS(CANIFORS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    CANIFORS_MAXIMA(CANIFORS_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    CANIS(CANIS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    CARCEREM_AQUATICUM (CARCEREM_AQUATICUM.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    CARPE_RETRACTUM(CARPE_RETRACTUM.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    CARTOMANCIE(CARTOMANCIE.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    CAVE_INIMICUM(CAVE_INIMICUM.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    CELATUM(CELATUM.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    CHARTIA(CHARTIA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    CISTEM_APERIO(CISTEM_APERIO.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    COLLOPORTUS(COLLOPORTUS.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    COLOVARIA(COLOVARIA.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    COLOVARIA_ALBUM(COLOVARIA_ALBUM.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    COLOVARIA_AURANTIACO(COLOVARIA_AURANTIACO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    COLOVARIA_CAERULUS(COLOVARIA_CAERULUS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    COLOVARIA_FLAVO(COLOVARIA_FLAVO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    COLOVARIA_OSTRUM(COLOVARIA_OSTRUM.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    COLOVARIA_VERIDI(COLOVARIA_VERIDI.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    COLOVARIA_VERMICULO(COLOVARIA_VERMICULO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    COMETES(COMETES.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    COMETES_DUO(COMETES_DUO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    CONFUNDO(CONFUNDO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    CONFUNDUS_DUO(CONFUNDUS_DUO.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    CRESCERE_PROTEGAT(CRESCERE_PROTEGAT.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    DEFODIO(DEFODIO.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    DELETRIUS(DELETRIUS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    DEPRIMO(DEPRIMO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    DEPULSO(DEPULSO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    DIAMAS_REPARO(DIAMAS_REPARO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    DIFFINDO(DIFFINDO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    DISSENDIUM(DISSENDIUM.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    DRACONIFORS(DRACONIFORS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN* 2),
    DUCKLIFORS(DUCKLIFORS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    DUCKLIFORS_MAXIMA(DUCKLIFORS_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN* 2),
    DURO(DURO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    EBUBLIO(EBUBLIO.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    ENGORGIO(ENGORGIO.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    ENTOMORPHIS(ENTOMORPHIS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN* 2),
    EPISKEY(EPISKEY.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    ET_INTERFICIAM_ANIMAM_LIGAVERIS(ET_INTERFICIAM_ANIMAM_LIGAVERIS.class, MagicLevel.EXPERT, O2Spell.DEFAULT_COOLDOWN),
    EQUUS(EQUUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    EQUIFORS(EQUIFORS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    EQUIFORS_MAXIMA(EQUIFORS_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    EVANESCO(EVANESCO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    EVANESCO_MAXIMA(EVANESCO_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    EXPELLIARMUS(EXPELLIARMUS.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    FATUUS_AURUM(FATUUS_AURUM.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    FELIFORS(FELIFORS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    FELIFORS_MAXIMA(FELIFORS_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    FELIFORS_MEDIUS(FELIFORS_MEDIUS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    FELIS(FELIS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    FIANTO_DURI(FIANTO_DURI.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    FIENDFYRE(FIENDFYRE.class, MagicLevel.EXPERT, O2Spell.DEFAULT_COOLDOWN),
    FINESTRA(FINESTRA.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    FINITE_INCANTATEM(FINITE_INCANTATEM.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    FLAGRANTE(FLAGRANTE.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    FLIPENDO(FLIPENDO.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    FRANGE_LIGNEA(FRANGE_LIGNEA.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    FUMOS(FUMOS.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    FUMOS_DUO(FUMOS_DUO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    GEMINO(GEMINO.class, MagicLevel.EXPERT, O2Spell.DEFAULT_COOLDOWN),
    // todo add GEMINIO the charm - https://harrypotter.fandom.com/wiki/Doubling_Charm
    GLACIUS(GLACIUS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    GLACIUS_DUO(GLACIUS_DUO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    GLACIUS_TRIA(GLACIUS_TRIA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    HARMONIA_NECTERE_PASSUS(HARMONIA_NECTERE_PASSUS.class, MagicLevel.EXPERT, O2Spell.DEFAULT_COOLDOWN),
    HERBIFORS(HERBIFORS.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    HERBIVICUS(HERBIVICUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    HORREAT_PROTEGAT(HORREAT_PROTEGAT.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    IMMOBULUS(IMMOBULUS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    IMPEDIMENTA(IMPEDIMENTA.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    INCENDIO(INCENDIO.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    INCENDIO_DUO(INCENDIO_DUO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    INCENDIO_TRIA(INCENDIO_TRIA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    INFORMOUS(INFORMOUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    INTUEOR(INTUEOR.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    LACARNUM_INFLAMARI(LACARNUM_INFLAMARI.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    LAMA(LAMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    LAPIFORS(net.pottercraft.ollivanders2.spell.LAPIFORS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    LAPIFORS_MAXIMA(LAPIFORS_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    LAPIFORS_MEDIUS(LAPIFORS_MEDIUS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    LEGILIMENS(LEGILIMENS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    LEPUS_SACCULUM(LEPUS_SACCULUM.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    LEVICORPUS(LEVICORPUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    LIBERACORPUS(LIBERACORPUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    LIGATIS_COR(LIGATIS_COR.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    LOQUELA_INEPTIAS(LOQUELA_INEPTIAS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    LUMOS(LUMOS.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN / 2),
    LUMOS_CAERULEUM(LUMOS_CAERULEUM.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    LUMOS_DUO(LUMOS_DUO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    LUMOS_FERVENS(LUMOS_FERVENS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    LUMOS_MAXIMA(LUMOS_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    // todo LUMOS_SOLEM(LUMOS_SOLEM.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    MANTEIA_KENTAVROS(MANTEIA_KENTAVROS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    MEGA_PYRO_PRASINA(MEGA_PYRO_PRASINA.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    MELOFORS(MELOFORS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    METELOJINX(METELOJINX.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    METELOJINX_RECANTO(METELOJINX_RECANTO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    MOLLIARE(MOLLIARE.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    MORSMORDRE(MORSMORDRE.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    MORTUOS_SUSCITATE(MORTUOS_SUSCITATE.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    MOV_FOTIA(MOV_FOTIA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    MUCUS_AD_NAUSEAM(MUCUS_AD_NAUSEAM.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    MUFFLIATO(MUFFLIATO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    MULTICORFORS(MULTICORFORS.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    NOX(NOX.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN / 2),
    NULLUM_APPAREBIT(NULLUM_APPAREBIT.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    NULLUM_EVANESCUNT(NULLUM_EVANESCUNT.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    OBLIVIATE(OBLIVIATE.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    OBSCURO(OBSCURO.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    OPPUGNO(OPPUGNO.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    OVOGNOSIS(OVOGNOSIS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    PACK(PACK.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    PARTIS_TEMPORUS(PARTIS_TEMPORUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    PERICULUM(PERICULUM.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    PERICULUM_DUO(PERICULUM_DUO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    PERMURATE(PERMURATE.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    PETRIFICUS_TOTALUS(PETRIFICUS_TOTALUS.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    PIERTOTUM_LOCOMOTOR(PIERTOTUM_LOCOMOTOR.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    POINT_ME(POINT_ME.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN / 2),
    PORFYRO_ASTERI(PORFYRO_ASTERI.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    PORFYRO_ASTERI_DUO(PORFYRO_ASTERI_DUO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    PORFYRO_ASTERI_TRIA(PORFYRO_ASTERI_TRIA.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    PORTUS(PORTUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    PRIOR_INCANTATO(PRIOR_INCANTATO.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    PROPHETEIA(PROPHETEIA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    PROTEGO(PROTEGO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    PROTEGO_DIABOLICA(PROTEGO_DIABOLICA.class, MagicLevel.EXPERT, O2Spell.DEFAULT_COOLDOWN),
    PROTEGO_HORRIBILIS(PROTEGO_HORRIBILIS.class, MagicLevel.EXPERT, O2Spell.DEFAULT_COOLDOWN),
    PROTEGO_MAXIMA(PROTEGO_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    PROTEGO_TOTALUM(PROTEGO_TOTALUM.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    PULLUS(PULLUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    PYRO_PRASINA(PYRO_PRASINA.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    PYROSVESTIRAS(PYROSVESTIRAS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    RANACULUS_AMPHORAM(RANACULUS_AMPHORAM.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    REDUCIO(REDUCIO.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    REDUCTO(REDUCTO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    REPARIFARGE(REPARIFARGE.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    REPARIFORS(REPARIFORS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    REPARO(REPARO.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    REPELLO_MUGGLETON(REPELLO_MUGGLETON.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    REPLETUS(REPLETUS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    RICTUSEMPRA(RICTUSEMPRA.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    SCARABAEUS_FIBULUM(SCARABAEUS_FIBULUM.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    SCUTO_CONTERAM(SCUTO_CONTERAM.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    SILENCIO(SILENCIO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    SKURGE(SKURGE.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    SNUFFLIFORS(SNUFFLIFORS.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    SPONGIFY(SPONGIFY.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    STUPEFY(STUPEFY.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    SUIFORS(SUIFORS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    SUIFORS_MAXIMA(SUIFORS_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    SUS(SUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    TARANTALLEGRA(TARANTALLEGRA.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    TERGEO(TERGEO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    TITILLANDO(TITILLANDO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    URSIFORS(URSIFORS.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    URSIFORS_MAXIMA(URSIFORS_MAXIMA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    URSUS(URSUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN * 2),
    VENTO_FOLIO(VENTO_FOLIO.class, MagicLevel.EXPERT, O2Spell.DEFAULT_COOLDOWN),
    VERA_VERTO(VERA_VERTO.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    VERDIMILLIOUS(VERDIMILLIOUS.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    VERDIMILLIOUS_DUO(VERDIMILLIOUS_DUO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    VERDIMILLIOUS_TRIA(VERDIMILLIOUS_TRIA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    VERMILLIOUS(VERMILLIOUS.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    VERMILLIOUS_DUO(VERMILLIOUS_DUO.class, MagicLevel.OWL, O2Spell.DEFAULT_COOLDOWN),
    VERMILLIOUS_TRIA(VERMILLIOUS_TRIA.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    VOLATUS(VOLATUS.class, MagicLevel.NEWT, O2Spell.DEFAULT_COOLDOWN),
    WINGARDIUM_LEVIOSA(WINGARDIUM_LEVIOSA.class, MagicLevel.BEGINNER, O2Spell.DEFAULT_COOLDOWN),
    //end
    ;

    /**
     * The {@link O2Spell} subclass that implements this spell.
     */
    private final Class<?> className;

    private final MagicLevel level;

    /**
     * How long the caster must wait between casts of this spell, in milliseconds.
     */
    private final long cooldown;

    /**
     * @param className the spell class that implements this spell type
     * @param level     the level of this spell
     * @param cooldown  the casting cooldown for this spell, in milliseconds
     */
    O2SpellType(@NotNull Class<?> className, MagicLevel level, long cooldown) {
        this.className = className;
        this.level = level;
        this.cooldown = cooldown;
    }

    /**
     * @return the spell class that implements this spell type
     */
    @NotNull
    public Class<?> getClassName() {
        return className;
    }

    /**
     * @return the level of this spell
     */
    @NotNull
    public MagicLevel getLevel() {
        return level;
    }

    /**
     * @return the casting cooldown for this spell type, in milliseconds
     */
    public long getCooldown() {
        return cooldown;
    }

    /**
     * Get the display name for this spell type, e.g. AQUA_ERUCTO -> "Aqua Eructo".
     *
     * @return the human-readable spell name
     */
    @NotNull
    public String getSpellName() {
        String spellTypeString = this.toString().toLowerCase();

        return Ollivanders2Common.firstLetterCapitalize(spellTypeString.replace("_", " "));
    }

    /**
     * Get a O2SpellType enum from a string. This should be used as the opposite of toString() on the enum.
     *
     * @param spellString the name of the spell type, ex. "AQUA_ERUCTO"
     * @return the spell type
     */
    @Nullable
    public static O2SpellType spellTypeFromString(@NotNull String spellString) {
        O2SpellType spellType = null;

        try {
            spellType = O2SpellType.valueOf(spellString);
        }
        catch (Exception e) {
            // this is expected when spellString is not a valid spell
        }

        return spellType;
    }
}
