package net.pottercraft.Ollivanders2;

/**
 * Represents allowable stationary spells.
 *
 */
public enum StationarySpells {
	ALIQUAM_FLOO,
	COLLOPORTUS,
	MUFFLIATO,
	HARMONIA_NECTERE_PASSUS,
	HORCRUX,
	NULLUM_APPAREBIT,
	NULLUM_EVANESCUNT,
	PRAEPANDO,
	PROTEGO,
	PROTEGO_HORRIBILIS,
	PROTEGO_MAXIMA,
	PROTEGO_TOTALUM,
	REPELLO_MUGGLETON,
	SPONGIFY;
}