package net.pottercraft.Ollivanders2.Book;

/**
 * All Ollivanders2 books.
 *
 * @since 2.2.4
 */
public enum Books
{
   A_BEGINNERS_GUIDE_TO_TRANSFIGURATION,
   ACHIEVEMENTS_IN_CHARMING,
   ADVANCED_FIREWORKS,
   ADVANCED_TRANSFIGURATION,
   BASIC_FIREWORKS,
   BASIC_HEXES,
   BREAK_WITH_A_BANSHEE,
   CHADWICKS_CHARMS,
   CONFRONTING_THE_FACELESS,
   CURSES_AND_COUNTERCURSES,
   ESSENTIAL_DARK_ARTS,
   EXTREME_INCANTATIONS,
   GADDING_WITH_GHOULS,
   HARMONIOUS_CONNECTIONS,
   HOLIDAYS_WITH_HAGS,
   INTERMEDIATE_TRANSFIGURATION,
   JINXES_FOR_THE_JINXED,
   MAGICK_MOSTE_EVILE,
   MODERN_MAGICAL_TRANSPORTATION,
   NUMEROLOGY_AND_GRAMMATICA,
   PRACTICAL_DEFENSIVE_MAGIC,
   QUINTESSENCE_A_QUEST,
   SECRETS_OF_THE_DARKEST_ART,
   SECRETS_OF_WANDLORE,
   STANDARD_BOOK_OF_SPELLS_GRADE_1,
   STANDARD_BOOK_OF_SPELLS_GRADE_2,
   STANDARD_BOOK_OF_SPELLS_GRADE_3,
   STANDARD_BOOK_OF_SPELLS_GRADE_4,
   STANDARD_BOOK_OF_SPELLS_GRADE_5,
   STANDARD_BOOK_OF_SPELLS_GRADE_6,
   STANDARD_BOOK_OF_SPELLS_GRADE_7,
   THE_DARK_FORCES,
   THE_HEALERS_HELPMATE,
   TRAVELS_WITH_TROLLS,
   VOYAGES_WITH_VAMPIRES,
   WANDERINGS_WITH_WEREWOLVES,
   WORLD_OF_COLOR,
   YEAR_WITH_A_YETI,
}
